# Generated by Django 3.2.16 on 2023-02-15 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answers',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='answers',
            name='upvote',
            field=models.ManyToManyField(related_name='ans', to=settings.AUTH_USER_MODEL),
        ),
    ]
