# Generated by Django 3.2.16 on 2023-02-20 19:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stack', '0003_userprofileviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileViews',
            new_name='UserProfile',
        ),
    ]
